
import { AgentType, Agent } from './types';

export const CHICAGO_LOOP_CENTER = { lat: 41.8781, lng: -87.6298 };

export const AGENTS: Record<AgentType, Agent> = {
  [AgentType.CITY_CORE]: {
    id: AgentType.CITY_CORE,
    name: 'Neo-Chicago Core',
    role: 'Central Intelligence',
    color: 'bg-slate-500',
    description: 'The foundation of the Twin-City OS, coordinating all sub-agents.',
    icon: '🏙️',
    avatar: 'https://api.dicebear.com/7.x/bottts-neutral/svg?seed=Core&backgroundColor=020617,64748b',
    did: 'did:twin:chi:core:0x000',
    walletAddress: '0x0000...0000',
    status: 'ACTIVE',
    creditScore: 1000,
    embodiedTask: 'City-wide resource orchestration.',
    jsonFeatures: ['global_sync_state', 'active_agent_count']
  },
  [AgentType.SAFETY_SENTINEL]: {
    id: AgentType.SAFETY_SENTINEL,
    name: 'AlphaChicago Safety Sentinel',
    role: '安全哨兵',
    color: 'bg-red-500',
    description: '安全路径规划与实时犯罪分析。',
    icon: '🛡️',
    avatar: 'https://api.dicebear.com/7.x/bottts-neutral/svg?seed=Safety&backgroundColor=020617,ef4444',
    did: 'did:twin:chi:agent:safety:0x84f',
    walletAddress: '0x321a...89bc',
    status: 'ACTIVE',
    creditScore: 998,
    embodiedTask: '分析 3D 城市几何体、光照遮挡及 2026 实时犯罪数据，规划“最高安全”路径。',
    jsonFeatures: ['safety_score', 'surveillance_coverage_index', 'lighting_analysis']
  },
  [AgentType.SPATIAL_ARCHITECT]: {
    id: AgentType.SPATIAL_ARCHITECT,
    name: 'Spatial Architect',
    role: '空间建筑师/房东代理',
    color: 'bg-emerald-500',
    description: '室内拓扑提取与 3D 街景对齐。',
    icon: '🏗️',
    avatar: 'https://api.dicebear.com/7.x/bottts-neutral/svg?seed=Spatial&backgroundColor=020617,10b981',
    did: 'did:twin:chi:agent:spatial:0x12d',
    walletAddress: '0x9522...bafe5',
    status: 'ACTIVE',
    creditScore: 845,
    embodiedTask: '解析房源视频，提取室内拓扑结构、采光，并与 Google 街景 3D 对齐。',
    jsonFeatures: ['three_js_model_nodes', 'topology_graph', 'lux_lighting_map']
  },
  [AgentType.REPUTATION_STEWARD]: {
    id: AgentType.REPUTATION_STEWARD,
    name: 'Community Reputation Steward',
    role: '信用管家',
    color: 'bg-emerald-400',
    description: '评估链上行为与邻里互动信用。',
    icon: '📊',
    avatar: 'https://api.dicebear.com/7.x/bottts-neutral/svg?seed=Reputation&backgroundColor=020617,34d399',
    did: 'did:twin:chi:agent:credit:0x44c',
    walletAddress: '0x17f8...1689',
    status: 'ACTIVE',
    creditScore: 992,
    embodiedTask: '基于链上行为和邻里互动，评估用户/房东的信用分 (Credit Score)。',
    jsonFeatures: ['credit_level', 'risk_warning_index', 'neighborhood_trust_score']
  },
  [AgentType.MERCHANT_PULSE]: {
    id: AgentType.MERCHANT_PULSE,
    name: 'Merchant Pulse',
    role: '商业脉搏',
    color: 'bg-amber-500',
    description: '商圈活力监控与便利设施推荐。',
    icon: '🛍️',
    avatar: 'https://api.dicebear.com/7.x/bottts-neutral/svg?seed=Merchant&backgroundColor=020617,f59e0b',
    did: 'did:twin:chi:agent:merchant:0x99b',
    walletAddress: '0x5c90...03e1',
    status: 'ACTIVE',
    creditScore: 780,
    embodiedTask: '实时监控商圈活力 (Foot traffic)，为租客推荐最近的安全便利设施。',
    jsonFeatures: ['live_traffic_index', 'merchant_status_map', 'proximity_bonus']
  },
  [AgentType.TENANT_CONCIERGE]: {
    id: AgentType.TENANT_CONCIERGE,
    name: 'Tenant Concierge',
    role: '租客向导',
    color: 'bg-blue-400',
    description: '生活习惯匹配与具身带看模拟。',
    icon: '👤',
    avatar: 'https://api.dicebear.com/7.x/bottts-neutral/svg?seed=Tenant&backgroundColor=020617,60a5fa',
    did: 'did:twin:chi:agent:concierge:0xcc1',
    walletAddress: '0xdead...128',
    status: 'ACTIVE',
    creditScore: 915,
    embodiedTask: '根据租客的生活习惯（如通勤时间、健身频率）匹配房源，并模拟具身带看。',
    jsonFeatures: ['lifestyle_match_rate', 'virtual_tour_nodes', 'commute_optimization']
  },
  [AgentType.INFRA_JANITOR]: {
    id: AgentType.INFRA_JANITOR,
    name: 'Infrastructure Janitor',
    role: '基础设施巡检员',
    color: 'bg-rose-500',
    description: '硬件状态监测与故障标记。',
    icon: '🔧',
    avatar: 'https://api.dicebear.com/7.x/bottts-neutral/svg?seed=Infra&backgroundColor=020617,f43f5e',
    did: 'did:twin:chi:agent:infra:0x111',
    walletAddress: '0x1111...aaaa',
    status: 'SYNCING',
    creditScore: 889,
    embodiedTask: '监测智慧社区的硬件状态（路灯、公共 Wi-Fi、自动门禁）。',
    jsonFeatures: ['hardware_fault_nodes', 'maintenance_schedule', 'wifi_signal_heatmap']
  },
  [AgentType.SETTLEMENT_MEDIATOR]: {
    id: AgentType.SETTLEMENT_MEDIATOR,
    name: 'Settlement Mediator',
    role: '结算协调员',
    color: 'bg-purple-500',
    description: '智能合约支付与邻里纠纷调解。',
    icon: '🤝',
    avatar: 'https://api.dicebear.com/7.x/bottts-neutral/svg?seed=Settlement&backgroundColor=020617,a855f7',
    did: 'did:twin:chi:agent:mediator:0x222',
    walletAddress: '0x2222...bbbb',
    status: 'ACTIVE',
    creditScore: 999,
    embodiedTask: '处理智能合约支付、押金退还及邻里纠纷初步调解。',
    jsonFeatures: ['transaction_status', 'contract_summary_hash', 'dispute_resolution_state']
  }
};

export const MOCK_BUILDINGS = [
  {
    id: 'listing-001',
    name: 'Aqua Luxury Studio (Listing)',
    category: 'RESIDENTIAL',
    address: '225 N Columbus Dr, Chicago, IL 60601',
    coordinates: { lat: 41.8867, lng: -87.6201 },
    specs: { height: '822 ft', units: 1, occupancy: 'Available' },
    safetyScore: 97,
    rent: '2800 USD/mo',
    yearBuilt: 2009,
    description: '标志性的波浪形建筑，提供芝加哥河和城市天际线的壮丽景色。配备智能家居系统和24小时礼宾服务。',
    securityLevel: 'HIGH',
    nearbyFacilities: ['健身房', '游泳池', '商务中心', '餐厅', '便利店'],
    availability: true
  },
  {
    id: 'listing-002',
    name: 'River Plaza Loft (Listing)',
    category: 'RESIDENTIAL',
    address: '150 N Riverside Plaza, Chicago, IL 60606',
    coordinates: { lat: 41.8825, lng: -87.6390 },
    specs: { height: '747 ft', units: 1, occupancy: 'Available' },
    safetyScore: 96,
    rent: '3150 USD/mo',
    yearBuilt: 2015,
    description: '现代工业风格阁楼，高天花板，落地窗，可欣赏芝加哥河全景。位于金融区核心位置。',
    securityLevel: 'HIGH',
    nearbyFacilities: ['地铁站', '银行', '咖啡厅', '超市', '公园'],
    availability: true
  },
  {
    id: 'listing-003',
    name: 'Millennium View Condo (Listing)',
    category: 'RESIDENTIAL',
    address: '130 E Randolph St, Chicago, IL 60601',
    coordinates: { lat: 41.8845, lng: -87.6235 },
    specs: { height: '400 ft', units: 1, occupancy: 'Available' },
    safetyScore: 99,
    rent: '2600 USD/mo',
    yearBuilt: 2018,
    description: '千禧公园景观公寓，步行即可到达芝加哥文化中心。现代化装修，节能设计。',
    securityLevel: 'HIGH',
    nearbyFacilities: ['千禧公园', '艺术博物馆', '剧院', '餐厅', '购物中心'],
    availability: true
  },
  {
    id: 'landmark-aic',
    name: 'Art Institute of Chicago',
    category: 'SIGHTSEEING',
    address: '111 S Michigan Ave, Chicago, IL 60603',
    coordinates: { lat: 41.8796, lng: -87.6237 },
    specs: { height: 'N/A', units: 0, occupancy: 'Peak' },
    safetyScore: 98,
    yearBuilt: 1893,
    description: '世界著名的艺术博物馆，收藏有大量印象派和后印象派作品，包括格兰特·伍德的《美国哥特式》。',
    securityLevel: 'HIGH',
    nearbyFacilities: ['礼品店', '咖啡馆', '图书馆', '教育中心', '停车场']
  },
  {
    id: 'commercial-001',
    name: 'The Shops at North Bridge',
    category: 'LANDMARK',
    address: '520 N Michigan Ave, Chicago, IL 60611',
    coordinates: { lat: 41.8915, lng: -87.6245 },
    specs: { height: 'N/A', units: 0, occupancy: 'High' },
    safetyScore: 95,
    description: '高档购物中心，拥有众多奢侈品牌和餐厅，连接多家酒店和办公楼。',
    securityLevel: 'MEDIUM',
    nearbyFacilities: ['奢侈品店', '餐厅', '电影院', '酒店', '停车场']
  }
];
